/* UI sin dependencias; estado serializado solo en este navegador. */
(()=>{'use strict';
const E=window.ConectaEngine, DATA=window.CONECTA_DATA, KEY='conecta-hex-ud1-game-v1';
const R=['F','D','I','O','H'], resNames={F:'Financiación',D:'Datos',I:'Tecnología IT',O:'Equipamiento OT',H:'Formación'}, color={F:'#d89951',D:'#4399b1',I:'#6876cb',O:'#ba6875',H:'#70ab72'}, pc={A:'#9de6b8',B:'#f4b783',C:'#9fbaf2',D:'#e0a7d9'};
const $=id=>document.getElementById(id);let state=null,quizInterval=null,marketInterval=null,quizDeadline=0,marketDeadline=0,toastTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const who=id=>state?.players.find(p=>p.id===id);
const legal=()=>state?E.legal(state).actions:[];
const has=(type,pred=()=>true)=>legal().some(a=>a.type===type&&pred(a));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(err){notify('No se ha podido guardar la partida en este navegador.');}}
function notify(text){const el=$('toast');el.textContent=text;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),3800);}
function stopQuiz(){clearInterval(quizInterval);quizInterval=null;}
function stopMarket(){clearInterval(marketInterval);marketInterval=null;}
function recordChanges(before,after,label){const entries=Array.isArray(before.resourceLog)?before.resourceLog.slice(-7):[];let added=0;for(const p of after.players){const was=before.players.find(x=>x.id===p.id);const changes=R.map(r=>({r,n:p.resources[r]-was.resources[r]})).filter(x=>x.n!==0);if(changes.length){entries.push(`${label} · ${p.id}: ${changes.map(x=>`${x.n>0?'+':''}${x.n} ${x.r}`).join(', ')}`);added++;}}if(!added&&['Oportunidad (6)','Reunir'].includes(label))entries.push(`${label}: tope 9; no se sumó recurso.`);after.resourceLog=entries.slice(-8);}
function act(action,{quiet=false}={}){try{let before=state,prev=state.phase,prevCurrent=state.current;state=E.apply(state,action);const labels={place:'Colocación y producción',choose:'Oportunidad (6)',bank:'Banco 3:1',accept:'Intercambio',gather:'Reunir',expand:'Expansión',answer:'Proyecto',endTurn:'Fin de turno'};let label=labels[action.type]||'Movimiento';if(state.round!==before.round)label+=` · producción ronda ${state.round} (dados ${state.rolls.join(' y ')})`;recordChanges(before,state,label);save();render();if(!quiet&&state.phase==='finished')endDialog();else if(!quiet&&prevCurrent!==state.current&&state.phase!=='finished'&&who(state.current)?.kind==='human'&&prev!=='setup')notify('Ahora le toca a la empresa '+state.current+'.');advanceBots();return true;}catch(err){notify(err.message||'Acción no permitida');return false;}}
function advanceBots(){if(!state||state.phase==='finished'||who(state.current)?.kind!=='bot')return;try{const before=state;state=E.botTurn(state);recordChanges(before,state,`Balance neto bots/producción${state.round!==before.round?' · dados '+state.rolls.join(' y '):''}`);save();render();if(state.phase==='finished')endDialog();else if(who(state.current)?.kind==='human')notify('Turno de la empresa '+state.current+'.');}catch(err){notify('Error en el turno automático: '+err.message);}}
function button(label,fn,cls='quiet'){let b=document.createElement('button');b.textContent=label;b.className=cls;b.addEventListener('click',fn);return b;}
function dialogChoice(title,copy,entries,{cancel=true,eyebrow='ELIGE UNA OPCIÓN'}={}){const d=$('choice');$('choice-eyebrow').textContent=eyebrow;$('choice-title').textContent=title;$('choice-copy').textContent=copy;$('choice-options').replaceChildren(...entries.map(({label,fn})=>button(label,()=>{d.close();fn();})));$('choice-cancel').classList.toggle('hidden',!cancel);if(!d.open)d.showModal();}
function chooseResource(title,copy,cb){dialogChoice(title,copy,R.map(r=>({label:r+' · '+resNames[r]+(who(state.current)?.resources[r]===9?' (tope 9; no sumará)':''),fn:()=>cb(r)})));}
function tileGeometry(){const radius=48,parts=[];for(const h of DATA.board){const x=250+Math.sqrt(3)*radius*(h.q+h.r/2),y=240+1.5*radius*h.r;parts.push({h,x,y});}return parts;}
function renderBoard(){const holder=$('board');holder.replaceChildren();const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 500 480');svg.setAttribute('role','img');svg.setAttribute('aria-label','Tablero de diecinueve casillas hexagonales');
const NS='http://www.w3.org/2000/svg', make=(tag,attrs)=>{const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el;};
for(const {h,x,y} of tileGeometry()){let owner=state?.players.find(p=>p.centers.includes(h.id)),places=state?.phase==='setup'&&has('place',a=>a.hex===h.id),extensions=state?.phase==='actions'&&!state.pendingChallenge&&has('expand',a=>a.hex===h.id);const g=make('g',{class:'tile'+((places||extensions)&&who(state.current)?.kind==='human'?' available':''),tabindex:(places||extensions)?'0':'-1',role:'button','aria-label':`Casilla ${h.id}, ${resNames[h.type]}${owner?', centro de empresa '+owner.id:''}`});const title=make('title',{});title.textContent=`Casilla ${String(h.id).padStart(2,'0')} · ${resNames[h.type]}${owner?' · Empresa '+owner.id:''}`;g.appendChild(title);let points=[];for(let i=0;i<6;i++){let a=Math.PI/3*i+Math.PI/6;points.push(`${x+48*Math.cos(a)},${y+48*Math.sin(a)}`);}g.appendChild(make('polygon',{points:points.join(' '),fill:color[h.type],class:'hex',opacity:owner?'1':'0.9'}));const small=make('text',{x,y:y+19,class:'hex-small'});small.textContent=String(h.id).padStart(2,'0');g.appendChild(small);const text=make('text',{x,y:y-9,class:'hex-label'});text.textContent=h.type;g.appendChild(text);
if(owner){let badge=make('circle',{cx:x+25,cy:y-26,r:15,fill:pc[owner.id],class:'owner-badge'}),label=make('text',{x:x+25,y:y-25,class:'owner-text'});label.textContent=owner.id;g.append(badge,label);}
if((places||extensions)&&who(state.current)?.kind==='human'){let click=()=>{if(places)act({type:'place',hex:h.id});else{const options=legal().filter(a=>a.type==='expand'&&a.hex===h.id);act(options[0]);}};g.addEventListener('click',click);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click();}});}svg.appendChild(g);}
if(state)for(const p of state.players)for(const [from,to] of p.links){let a=tileGeometry().find(v=>v.h.id===from),b=tileGeometry().find(v=>v.h.id===to);if(a&&b){const line=make('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:pc[p.id],'stroke-width':4,'stroke-dasharray':'4 3',opacity:'.9','pointer-events':'none'});svg.insertBefore(line,svg.firstChild);}}
holder.appendChild(svg);}
function renderPlayers(){const box=$('players');box.replaceChildren();if(!state)return;for(const p of state.players){let row=document.createElement('div');row.className='player'+(state.current===p.id?' active':'');row.innerHTML=`<span class="avatar" style="background:${pc[p.id]}">${p.id}</span><span class="player-main"><b>Empresa ${p.id} ${p.kind==='bot'?'· IA':''}</b><small>${p.centers.length} centros · ${p.completed.length} proyectos · ${p.pending?'reto pendiente':'sin retos pendientes'}</small><small>${R.map(r=>`${r}${p.resources[r]}`).join(' · ')}</small></span><span class="points">${E.score(state,p.id)}<small class="muted"> pt</small></span>`;box.appendChild(row);}}
function renderProjects(){const box=$('projects');box.replaceChildren();for(const [f,title,sub] of [['P','Procesos','F + D + I + H'],['T','Tecnología','F + D + I + O'],['C','Personas y estrategia','F + D + 2H']]){let section=document.createElement('div');section.className='project-family';section.innerHTML=`<h3>${title}<small>${sub}</small></h3>`;for(const pr of E.projects.filter(x=>x.family===f)){let done=state&&who(state.active)?.completed.includes(pr.id);let enabled=state?.phase==='actions'&&!state.pendingChallenge&&who(state.current)?.kind==='human'&&has('project',a=>a.project===pr.id);let item=document.createElement('div');item.className='project'+(done?' done':'')+(enabled?' clickable':'');item.innerHTML=`<span>${pr.id}</span><span>${esc(pr.title)}</span><span class="cost">${Object.entries(pr.cost).map(([k,n])=>k+(n>1?'×'+n:'')).join(' ')}</span>`;if(enabled)item.addEventListener('click',()=>project(pr.id));section.appendChild(item);}box.appendChild(section);}}
function renderResources(){const box=$('resource-strip'),log=$('resource-log');box.replaceChildren();log.replaceChildren();$('resource-owner').textContent='';if(!state||state.phase==='finished')return;const p=who(state.phase==='production'||state.phase==='setup'||state.offer?state.current:state.active);$('resource-owner').textContent=`Recursos de la empresa ${p.id} · máximo 9 por tipo`;for(const r of R){let div=document.createElement('div');div.className='resource';div.style.setProperty('--resource',color[r]);div.innerHTML=`<b>${p.resources[r]}</b><small>${r} · ${resNames[r]}</small>`;box.appendChild(div);}const entries=state.resourceLog?.slice(-3)||[];if(entries.length){for(const text of entries){const row=document.createElement('p');row.textContent=text;log.appendChild(row);}}else log.textContent='Inicio: 1 de cada recurso. Los dados producen por centro y por tirada; el exceso sobre 9 se pierde.';}
function renderActions(){const box=$('actions');box.replaceChildren();if(!state)return;const current=who(state.current),human=current?.kind==='human';if(state.phase==='finished')return;if(!human){box.appendChild(button('Rivales en movimiento…',()=>{},'quiet wide'));return;}
function header(s){let h=document.createElement('div');h.className='action-head';h.textContent=s;box.appendChild(h);}function add(s,fn,cls='quiet'){box.appendChild(button(s,fn,cls));}
if(state.phase==='setup'){header('Coloca un centro en una casilla iluminada.');return;}
if(state.phase==='production'){header('Ha salido un 6: recurso de oportunidad.');add('Elegir recurso',()=>chooseResource('Oportunidad','Tu empresa elige un recurso por este 6; máximo 9 por tipo.',r=>act({type:'choose',resource:r})),'primary wide');return;}

if(state.phase==='market'){if(state.offer){let o=state.offer,receive=Object.entries(o.receive).map(([r,n])=>`${n} ${r}`).join(' + '),give=Object.entries(o.give).map(([r,n])=>`${n} ${r}`).join(' + ');header(`Empresa ${state.active} ofrece ${give} a ${o.to} a cambio de ${receive}.`);add('Aceptar',()=>act({type:'accept'}),'primary');add('Rechazar',()=>act({type:'reject'}));return;}
header('Mercado · 45 s · '+state.bankTrades+'/2 cambios bancarios');add('Banco · 3 por 1',bank);if(state.players.filter(p=>p.kind==='human').length>1)add('Negociar con otra persona',trade);add('Cerrar mercado →',()=>act({type:'closeMarket'}),'primary wide');return;}
if(state.phase==='actions'){if(state.pendingChallenge){header('Resuelve el reto para continuar.');add('Mostrar reto',showQuiz,'primary wide');return;}header(`Te quedan ${state.actionsLeft} acciones · ${state.expanded?'Expansión realizada · ':''}${state.challenged?'Reto intentado':''}`);if(state.actionsLeft){add('Reunir +1',()=>chooseResource('Reunir','Gasta una acción y cobra un recurso.',r=>act({type:'gather',resource:r})));add('Expandir · F D I',()=>notify('Elige en el tablero una casilla vecina iluminada.'),has('expand')?'quiet':'quiet');add('Proyecto · 2 pt',()=>{let opts=legal().filter(a=>a.type==='project');if(!opts.length){const p=who(state.active),min=p.completed.length>=5?4:p.completed.length>=3?3:2;notify(p.centers.length<min?`Necesitas ${min} centros para intentar tu ${p.completed.length+1}.º proyecto.`:'No tienes recursos suficientes o ya intentaste un reto este turno.');return;}dialogChoice('Elige un proyecto','Los recursos se pagan solo si aciertas.',opts.map(a=>({label:`${a.project} · ${E.projects.find(p=>p.id===a.project).title}`,fn:()=>project(a.project)})));});}add('Terminar turno →',()=>act({type:'endTurn'}),'primary wide');}}
function bank(){if(!has('bank')){notify('Necesitas 3 unidades iguales, un recurso receptor por debajo de 9 y menos de 2 cambios.');return;}const opts=legal().filter(a=>a.type==='bank'),types=[...new Set(opts.map(a=>a.give))];dialogChoice('Entrega 3 recursos','Recibes uno de otro tipo.',types.map(give=>({label:`3 ${give} · ${resNames[give]}`,fn:()=>dialogChoice('Recibe 1 recurso','El cambio no gasta una acción.',opts.filter(a=>a.give===give).map(({receive})=>({label:`1 ${receive} · ${resNames[receive]}`,fn:()=>act({type:'bank',give,receive})})))})));}
function trade(){const others=state.players.filter(p=>p.kind==='human'&&p.id!==state.active);dialogChoice('Negocia con otra empresa','La otra persona puede aceptar o rechazar.',others.map(p=>({label:`Empresa ${p.id}`,fn:()=>offerForm(p.id)})));}
function offerForm(to){const box=$('choice-options'),d=$('choice');$('choice-eyebrow').textContent='ACUERDO VOLUNTARIO';$('choice-title').textContent=`Empresa ${state.active} → ${to}`;$('choice-copy').textContent='Cada parte entrega al menos una unidad. No se intercambian puntos ni proyectos.';box.replaceChildren();const option=arr=>arr.map(x=>`<option value="${x}">${x}</option>`).join('');box.innerHTML=`<label>Ofrezco <select id="give-type">${option(R)}</select> <select id="give-qty">${option([1,2,3,4,5,6,7,8,9])}</select></label><label>Pido <select id="take-type">${option(R)}</select> <select id="take-qty">${option([1,2,3,4,5,6,7,8,9])}</select></label>`;const given=$('give-type'),taken=$('take-type');const syncTypes=()=>{for(const o of taken.options)o.disabled=o.value===given.value;if(taken.value===given.value)taken.value=R.find(r=>r!==given.value);};given.addEventListener('change',syncTypes);syncTypes();box.appendChild(button('Proponer intercambio',()=>{let give=$('give-type').value,receive=$('take-type').value,n=Number($('give-qty').value),m=Number($('take-qty').value);if(act({type:'offer',to,give:{[give]:n},receive:{[receive]:m}}))d.close();},'primary wide'));d.showModal();}
function project(id){if(act({type:'project',project:id},{quiet:true}))showQuiz();}
function showQuiz(){if(!state?.pendingChallenge)return;const q=state.pendingChallenge,c=state.cards.find(x=>x.id===q.cardId),d=$('quiz');stopQuiz();$('quiz-family').textContent=`${q.family==='P'?'PROCESOS':q.family==='T'?'TECNOLOGÍA':'PERSONAS'} · ${esc(c.id)} · ${q.retry?'REINTENTO':'PRIMER INTENTO'}`;$('quiz-title').textContent=c.title;$('quiz-idea').textContent=q.idea||'';$('quiz-idea').classList.toggle('hidden',!q.idea);$('quiz-question').textContent=q.question;$('quiz-feedback').classList.add('hidden');$('quiz-continue').classList.add('hidden');const options=$('quiz-options');options.replaceChildren(...q.options.map((text,i)=>button('ABC'[i]+' · '+text,()=>answer('ABC'[i]))));if(!d.open)d.showModal();quizDeadline=Date.now()+60000;tickQuiz();quizInterval=setInterval(tickQuiz,250);}
function tickQuiz(){let sec=Math.max(0,Math.ceil((quizDeadline-Date.now())/1000));$('quiz-timer').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;$('quiz-timer').classList.toggle('urgent',sec<=10);if(sec===0&&state?.pendingChallenge)answer(null);}
function answer(value){stopQuiz();if(!state?.pendingChallenge)return;const ok=act(value?{type:'answer',answer:value}:{type:'timeout'},{quiet:true});if(!ok)return;const result=state.lastChallenge;const box=$('quiz-feedback');box.className='feedback'+(result.correct?'':' wrong');box.textContent=(result.correct?'¡Correcto! Proyecto completado. ':'No es correcto: recursos conservados y carta pendiente para tu próximo turno. ')+`Respuesta: ${result.answer}. ${result.explanation}`;$('quiz-options').replaceChildren();$('quiz-continue').classList.remove('hidden');}
function endDialog(){const names=E.winner(state).join(' y ');dialogChoice('Partida terminada',`Gana ${names?'la empresa '+names:'sin ganador'} · ronda ${state.round}. El resultado sirve para repasar, no equivale a una nota académica.`,[{label:'Ver tablero final',fn:()=>{}},{label:'Nueva partida',fn:()=>newGame()}],{cancel:false,eyebrow:'BALANCE FINAL'});}
function render(){if(!state)return;renderBoard();renderPlayers();renderResources();renderProjects();renderActions();$('round').textContent=state.phase==='finished'?'Partida finalizada':`Ronda ${state.round}/12${state.finalRound?' · ronda final':''}`;$('rolls').textContent=state.rolls?.length?'Dados: '+state.rolls.join(' + ')+(state.phase==='production'&&state.productionRollIndex?' · resolviendo '+state.productionRollIndex+'.º':''):'—';const labels={setup:'Colocación inicial',production:'Producción de ronda',market:'Mercado',actions:'Dos acciones',finished:'Fin de partida'};$('turn-title').textContent=state.phase==='finished'?'Balance de la partida':`Empresa ${state.current} · ${labels[state.phase]}`;$('phase-description').textContent=state.phase==='setup'?`Centro ${Math.floor(state.setupIndex/state.players.length)+1}/2. Elige un hexágono vacío${who(state.current).centers.length?' de un tipo distinto':''}.`:state.phase==='production'?'Cada tirada se resuelve antes de los turnos.':state.phase==='market'?'El mercado se cierra antes de las dos acciones.':state.phase==='actions'?'Puedes reunir, expandir o intentar un proyecto.':'Los centros y proyectos dan puntos; diversifica P, T y C.';$('hint').textContent=state.phase==='setup'?'Elige una casilla resaltada para colocar tu centro.':state.phase==='actions'&&has('expand')?'Puedes expandir a una casilla vecina resaltada (F + D + I).':'Los centros producen recursos al inicio de cada ronda; las letras indican el recurso.';
if(state.phase==='market'&&!state.offer){if(!marketDeadline)marketDeadline=Date.now()+45000;if(!marketInterval)marketInterval=setInterval(()=>{if(Date.now()>=marketDeadline){stopMarket();marketDeadline=0;if(state?.phase==='market'&&!state.offer)act({type:'closeMarket'});}},300);}else if(state.phase!=='market'){stopMarket();marketDeadline=0;}}
function newGame(){if(state&&!confirm('¿Empezar una partida nueva y reemplazar la guardada?'))return;$('setup').showModal();}
function start(){let humans=Number($('humans').value),total=Number($('total').value);if(total<humans){$('total').value=String(humans);total=humans;}try{state=E.createGame({humans,bots:total-humans},DATA.board,DATA.cards);marketDeadline=0;stopQuiz();stopMarket();save();$('setup').close();render();advanceBots();}catch(err){notify(err.message);}}
$('humans').addEventListener('change',()=>{if(Number($('total').value)<Number($('humans').value))$('total').value=$('humans').value;});$('new-btn').addEventListener('click',newGame);$('start').addEventListener('click',start);$('resume').addEventListener('click',()=>$('setup').close());$('choice-cancel').addEventListener('click',()=>$('choice').close());$('quiz-continue').addEventListener('click',()=>{$('quiz').close();render();advanceBots();});$('rules-btn').addEventListener('click',()=>$('rules').showModal());$('rules-close').addEventListener('click',()=>$('rules').close());$('quiz').addEventListener('cancel',e=>{if(state?.pendingChallenge)e.preventDefault();});
try{let old=JSON.parse(localStorage.getItem(KEY));if(old&&Array.isArray(old.players)&&old.board?.length===19&&old.cards?.length===36&&['setup','production','impulse','market','actions','finished'].includes(old.phase)){state=old;if(state.phase==='impulse'){state.phase='market';save();}render();$('resume').classList.remove('hidden');$('setup').showModal();}else $('setup').showModal();}catch(err){$('setup').showModal();}
})();
